### ISSUE TITLE
Round playback rates to two decimals

### ISSUE THREAD

**Issue by dltmtt** [ritamsarmah/accelerate#9]
### Feature Description

Certain websites display the current playback rate in the video player as-is. I configured the speed up/down actions with a 0,1 step. In JavaScript, floating point operations are subject to round errors and result in long numbers which may not fit in a video player (see the screenshots for an example, the one with normal playback rate is for reference)
<img width="277" alt="Screenshot 2024-03-02 at 23 04 10" src="https://github.com/ritamsarmah/accelerate/assets/50383865/dceabc67-a769-43c5-8478-7211cb67b636">
<img width="268" alt="Screenshot 2024-03-02 at 23 04 17" src="https://github.com/ritamsarmah/accelerate/assets/50383865/225f0b30-e5ef-4c3f-9d86-3ef902fd3f55">
I suggest to apply a `.toFixed(2)` to the numbers after playback rate deltas addition. I'd do it myself but I'm not sure if changing JS files is enough for a Safari extension (I don't have XCode installed)

### Operating System

macOS

**Comment by dltmtt** [comment]
I've just seen that you already have a `ratechange` event listener, so it might be better to apply the rounding there

**Comment by ritamsarmah** [comment]
Hi @MDXZ-delti,

Thanks for the suggestion! This will be fixed accordingly by #10.
